name: test

on:
  push:
    branches:
      - main
    paths:
      - '**.js'
      - '**.ts'
      - 'package.json'
      - 'tsconfig.json'
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 20
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Lint
        run: yarn lint --no-fix

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 20
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Test
        run: yarn test
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage/
          retention-days: 1
      - uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: reports/
          retention-days: 1

  sonarcloud:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - uses: actions/download-artifact@v3
        with:
          name: coverage
          path: coverage/
      - uses: actions/download-artifact@v3
        with:
          name: test-reports
          path: reports/
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
